<a href="https://colab.research.google.com/github/AnkushSharmaGuragai/AI-ML/blob/main/worksheet0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def convert_units(conversion_type, value):
    """
    Converts units based on the selected conversion type.

    Parameters:
    conversion_type (int): The type of conversion selected by the user.
                           1 = meters to feet
                           2 = feet to meters
                           3 = kilograms to pounds
                           4 = pounds to kilograms
                           5 = liters to gallons
                           6 = gallons to liters
    value (float): The numeric value to convert.

    Returns:
    float: The converted value.
    """

    if conversion_type == 1:
        return value * 3.28084  # meters to feet
    elif conversion_type == 2:
        return value / 3.28084  # feet to meters
    elif conversion_type == 3:
        return value * 2.20462  # kg to pounds
    elif conversion_type == 4:
        return value / 2.20462  # pounds to kg
    elif conversion_type == 5:
        return value * 0.264172  # liters to gallons
    elif conversion_type == 6:
        return value / 0.264172  # gallons to liters
    else:
        return None


def main():
    print("Unit Conversion Program")
    print("1. Meters to Feet")
    print("2. Feet to Meters")
    print("3. Kilograms to Pounds")
    print("4. Pounds to Kilograms")
    print("5. Liters to Gallons")
    print("6. Gallons to Liters")

    try:
        choice = int(input("Choose conversion type (1-6): "))
        value = float(input("Enter the value to convert: "))

        result = convert_units(choice, value)

        if result is None:
            print("Unsupported conversion type.")
        else:
            print("Converted value:", result)

    except ValueError:
        print("Error: Please enter a valid number.")


if __name__ == "__main__":
    main()

Unit Conversion Program
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
Choose conversion type (1-6): 1
Enter the value to convert: 2
Converted value: 6.56168


In [ ]:
def calculate_sum(numbers):
    """
    Calculate the sum of a list of numbers.

    Parameters:
    numbers (list of float): List of numbers to sum.

    Returns:
    float: Sum of the numbers.
    """
    return sum(numbers)


def calculate_average(numbers):
    """
    Calculate the average of a list of numbers.

    Parameters:
    numbers (list of float): List of numbers to average.

    Returns:
    float: Average of the numbers.
    """
    return sum(numbers) / len(numbers)


def calculate_max(numbers):
    """
    Find the maximum value in a list of numbers.

    Parameters:
    numbers (list of float): List of numbers.

    Returns:
    float: Maximum number in the list.
    """
    return max(numbers)


def calculate_min(numbers):
    """
    Find the minimum value in a list of numbers.

    Parameters:
    numbers (list of float): List of numbers.

    Returns:
    float: Minimum number in the list.
    """
    return min(numbers)


def main():
    print("Mathematical Operations on a List of Numbers")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
        choice = int(input("Choose an operation (1-4): "))
        numbers_input = input("Enter a list of numbers separated by spaces: ").strip()

        if not numbers_input:
            raise ValueError("Empty input not allowed.")

        # Convert input string to list of floats
        numbers = [float(num) for num in numbers_input.split()]

        if choice == 1:
            result = calculate_sum(numbers)
        elif choice == 2:
            result = calculate_average(numbers)
        elif choice == 3:
            result = calculate_max(numbers)
        elif choice == 4:
            result = calculate_min(numbers)
        else:
            print("Invalid operation selected.")
            return

        print("Result:", result)

    except ValueError as ve:
        print("Error:", ve)


if __name__ == "__main__":
    main()

Mathematical Operations on a List of Numbers
1. Sum
2. Average
3. Maximum
4. Minimum
Choose an operation (1-4): 3
Enter a list of numbers separated by spaces: 2 3
Result: 3.0


In [ ]:
def extract_every_other(lst):
    """
    Extract every other element from a list, starting from the first element.

    Parameters:
    lst (list): The original list.

    Returns:
    list: A new list containing every other element from the original list.
    """
    return lst[::2]  # Take every 2nd element starting from index 0


# Example usage:
original_list = [1, 2, 3, 4, 5, 6]
result = extract_every_other(original_list)
print("Original list:", original_list)
print("Every other element:", result)

Original list: [1, 2, 3, 4, 5, 6]
Every other element: [1, 3, 5]


In [ ]:
def get_sublist(lst, start, end):
    """
    Return a sublist from a given list, from start index to end index (inclusive).

    Parameters:
    lst (list): The original list.
    start (int): Starting index (inclusive).
    end (int): Ending index (inclusive).

    Returns:
    list: A sublist from start to end index.
    """
    # Ensure end+1 because Python slicing is exclusive at the end
    return lst[start:end+1]


# Example usage:
original_list = [1, 2, 3, 4, 5, 6]
start_index = 2
end_index = 4
result = get_sublist(original_list, start_index, end_index)
print("Original list:", original_list)
print(f"Sublist from index {start_index} to {end_index}:", result)

Original list: [1, 2, 3, 4, 5, 6]
Sublist from index 2 to 4: [3, 4, 5]


In [ ]:
def reverse_list(lst):
    """
    Reverse a list using slicing.

    Parameters:
    lst (list): The original list.

    Returns:
    list: A new list with elements in reverse order.
    """
    return lst[::-1]  # Slicing with step -1 reverses the list


# Example usage:
original_list = [1, 2, 3, 4, 5]
reversed_list = reverse_list(original_list)

print("Original list:", original_list)
print("Reversed list:", reversed_list)

Original list: [1, 2, 3, 4, 5]
Reversed list: [5, 4, 3, 2, 1]


In [ ]:
def remove_first_last(lst):
    """
    Remove the first and last elements from a list using slicing.

    Parameters:
    lst (list): The original list.

    Returns:
    list: A sublist without the first and last elements.
    """
    return lst[1:-1]  # Slice from index 1 to one before the last element


# Example usage:
original_list = [1, 2, 3, 4, 5]
result = remove_first_last(original_list)

print("Original list:", original_list)
print("List without first and last elements:", result)

Original list: [1, 2, 3, 4, 5]
List without first and last elements: [2, 3, 4]


In [ ]:
def get_first_n(lst, n):
    """
    Extract the first n elements from a list using slicing.

    Parameters:
    lst (list): The original list.
    n (int): Number of elements to extract from the beginning.

    Returns:
    list: A sublist containing the first n elements.
    """
    return lst[:n]  # Slice from start up to index n (exclusive)


# Example usage:
original_list = [1, 2, 3, 4, 5]
n = 3
result = get_first_n(original_list, n)

print("Original list:", original_list)
print(f"First {n} elements:", result)

Original list: [1, 2, 3, 4, 5]
First 3 elements: [1, 2, 3]


In [ ]:
def get_last_n(lst, n):
    """
    Extract the last n elements from a list using slicing.

    Parameters:
    lst (list): The original list.
    n (int): Number of elements to extract from the end.

    Returns:
    list: A sublist containing the last n elements.
    """
    return lst[-n:]  # Slice from -n to the end of the list


# Example usage:
original_list = [1, 2, 3, 4, 5]
n = 2
result = get_last_n(original_list, n)

print("Original list:", original_list)
print(f"Last {n} elements:", result)

Original list: [1, 2, 3, 4, 5]
Last 2 elements: [4, 5]


In [ ]:
def reverse_skip(lst):
    """
    Extract every second element from a list in reverse order,
    starting from the second-to-last element.

    Parameters:
    lst (list): The original list.

    Returns:
    list: A new list containing every second element from the end, moving backward.
    """
    return lst[-2::-2]  # Start at second-to-last (-2), move backwards with step -2


# Example usage:
original_list = [1, 2, 3, 4, 5, 6]
result = reverse_skip(original_list)

print("Original list:", original_list)
print("Elements in reverse order, skipping one:", result)

Original list: [1, 2, 3, 4, 5, 6]
Elements in reverse order, skipping one: [5, 3, 1]


In [ ]:
def flatten(lst):
    """
    Flatten a nested list into a single list.

    Parameters:
    lst (list of lists): A nested list where each element is a list.

    Returns:
    list: A single flattened list containing all elements.
    """
    flat_list = []
    for sublist in lst:
        flat_list.extend(sublist)  # Add all elements of sublist to flat_list
    return flat_list


# Example usage:
nested_list = [[1, 2], [3, 4], [5]]
result = flatten(nested_list)

print("Nested list:", nested_list)
print("Flattened list:", result)

Nested list: [[1, 2], [3, 4], [5]]
Flattened list: [1, 2, 3, 4, 5]


In [ ]:
def access_nested_element(lst, indices):
    """
    Access a specific element from a nested list using a list of indices.

    Parameters:
    lst (list of lists): The nested list.
    indices (list of int): List of indices specifying the path to the element.

    Returns:
    The element at the specified position in the nested list.
    """
    element = lst
    for index in indices:
        element = element[index]  # Drill down to the next level
    return element


# Example usage:
nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
result = access_nested_element(nested_list, indices)

print("Nested list:", nested_list)
print(f"Element at indices {indices}:", result)

Nested list: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Element at indices [1, 2]: 6


In [ ]:
def sum_nested(lst):
    """
    Calculate the sum of all elements in a nested list, regardless of depth.

    Parameters:
    lst (list): A nested list containing numbers or other lists.

    Returns:
    int/float: The sum of all numeric elements in the nested list.
    """
    total = 0
    for element in lst:
        if isinstance(element, list):
            total += sum_nested(element)  # Recursively sum sublists
        else:
            total += element  # Add numbers directly
    return total


# Example usage:
nested_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(nested_list)

print("Nested list:", nested_list)
print("Sum of all elements:", result)

Nested list: [[1, 2], [3, [4, 5]], 6]
Sum of all elements: 21


In [ ]:
def remove_element(lst, elem):
    """
    Remove all occurrences of a specific element from a nested list.

    Parameters:
    lst (list of lists): The nested list.
    elem: The element to remove.

    Returns:
    list: A new nested list with the element removed from all sublists.
    """
    new_list = []
    for sublist in lst:
        if isinstance(sublist, list):
            # Remove the element from sublist using list comprehension
            filtered = [x for x in sublist if x != elem]
            new_list.append(filtered)
        else:
            # If the element itself is not a list, just keep it if it's not the element to remove
            if sublist != elem:
                new_list.append(sublist)
    return new_list


# Example usage:
nested_list = [[1, 2], [3, 2], [4, 5]]
element_to_remove = 2
result = remove_element(nested_list, element_to_remove)

print("Original nested list:", nested_list)
print(f"Nested list after removing {element_to_remove}:", result)

Original nested list: [[1, 2], [3, 2], [4, 5]]
Nested list after removing 2: [[1], [3], [4, 5]]


In [ ]:
def find_element_max(lst):
    """
    Find the maximum element in a nested list, regardless of depth.

    Parameters:
    lst (list): A nested list containing numbers or other lists.

    Returns:
    int/float: The maximum element in the nested list.
    """
    max_val = float('-inf')  # Start with the smallest possible value
    for element in lst:
        if isinstance(element, list):
            # Recursively find the maximum in the sublist
            sub_max = find_element_max(element)
            if sub_max > max_val:
                max_val = sub_max
        else:
            if element > max_val:
                max_val = element
    return max_val


# Example usage:
nested_list = [[1, 2], [3, [4, 5]], 6]
result = find_element_max(nested_list)

print("Nested list:", nested_list)
print("Maximum element:", result)

Nested list: [[1, 2], [3, [4, 5]], 6]
Maximum element: 6


In [ ]:
def count_occurrences(lst, elem):
    """
    Count how many times a specific element appears in a nested list.

    Parameters:
    lst (list): A nested list containing numbers or other lists.
    elem: The element to count.

    Returns:
    int: Number of times elem appears in the nested list.
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            # Recursively count occurrences in sublist
            count += count_occurrences(item, elem)
        else:
            if item == elem:
                count += 1
    return count


# Example usage:
nested_list = [[1, 2], [2, 3], [2, 4]]
element_to_count = 2
result = count_occurrences(nested_list, element_to_count)

print("Nested list:", nested_list)
print(f"Occurrences of {element_to_count}:", result)

Nested list: [[1, 2], [2, 3], [2, 4]]
Occurrences of 2: 3


In [ ]:
def deep_flatten(lst):
    """
    Flatten a deeply nested list (any depth) into a single list.

    Parameters:
    lst (list): A nested list of arbitrary depth.

    Returns:
    list: A single flattened list containing all elements.
    """
    flat_list = []
    for element in lst:
        if isinstance(element, list):
            # Recursively flatten sublists
            flat_list.extend(deep_flatten(element))
        else:
            flat_list.append(element)
    return flat_list


# Example usage:
nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(nested_list)

print("Deeply nested list:", nested_list)
print("Flattened list:", result)

Deeply nested list: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
Flattened list: [1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
def average_nested(lst):
    """
    Calculate the average of all elements in a nested list.

    Parameters:
    lst (list): A nested list containing numbers or other lists.

    Returns:
    float: The average of all numeric elements in the nested list.
    """
    def sum_count(sublist):
        """Helper function to recursively sum elements and count them."""
        total = 0
        count = 0
        for element in sublist:
            if isinstance(element, list):
                sub_total, sub_count = sum_count(element)
                total += sub_total
                count += sub_count
            else:
                total += element
                count += 1
        return total, count

    total_sum, total_count = sum_count(lst)
    if total_count == 0:
        return 0  # Avoid division by zero for empty list
    return total_sum / total_count


# Example usage:
nested_list = [[1, 2], [3, 4], [5, 6]]
result = average_nested(nested_list)

print("Nested list:", nested_list)
print("Average of all elements:", result)

Nested list: [[1, 2], [3, 4], [5, 6]]
Average of all elements: 3.5


In [ ]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("1. Empty 2x2 array:\n", empty_array)

# 2. Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("\n2. All-one 4x2 array:\n", ones_array)

# 3. Return a new array of given shape and type, filled with fill value
shape = (3, 3)       # Example shape
fill_value = 7        # Example fill value
filled_array = np.full(shape, fill_value)
print("\n3. Array filled with value {}:\n".format(fill_value), filled_array)

# 4. Return a new array of zeros with same shape and type as a given array
given_array = np.array([[5, 6, 7], [8, 9, 10]])
zeros_like_array = np.zeros_like(given_array)
print("\n4. Zeros array with same shape as given array:\n", zeros_like_array)

# 5. Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(given_array)
print("\n5. Ones array with same shape as given array:\n", ones_like_array)

# 6. Convert an existing list to a numpy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\n6. Numpy array from list {}:\n".format(new_list), numpy_array)

1. Empty 2x2 array:
 [[3.92144018e-315 0.00000000e+000]
 [2.14321575e-312             nan]]

2. All-one 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with value 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros array with same shape as given array:
 [[0 0 0]
 [0 0 0]]

5. Ones array with same shape as given array:
 [[1 1 1]
 [1 1 1]]

6. Numpy array from list [1, 2, 3, 4]:
 [1 2 3 4]


In [ ]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
array_10_49 = np.arange(10, 50)
print("1. Array with values from 10 to 49:\n", array_10_49)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(0, 9).reshape(3, 3)
print("\n2. 3x3 matrix with values 0 to 8:\n", matrix_3x3)

# 3. Create a 3x3 identity matrix
identity_3x3 = np.eye(3)
print("\n3. 3x3 identity matrix:\n", identity_3x3)

# 4. Create a random array of size 30 and find its mean
random_array_30 = np.random.random(30)
mean_random_array = random_array_30.mean()
print("\n4. Random array of size 30:\n", random_array_30)
print("Mean of random array:", mean_random_array)

# 5. Create a 10x10 array with random values and find min and max
random_array_10x10 = np.random.random((10, 10))
min_val = random_array_10x10.min()
max_val = random_array_10x10.max()
print("\n5. 10x10 random array:\n", random_array_10x10)
print("Minimum value:", min_val)
print("Maximum value:", max_val)

# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array_10 = np.zeros(10)
zero_array_10[4] = 1  # 5th element (index 4)
print("\n6. Zero array with 5th element replaced by 1:\n", zero_array_10)

# 7. Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\n7. Reversed array:\n", reversed_arr)

# 8. Create a 2D array with 1 on border and 0 inside
n, m = 5, 5  # Example size 5x5
border_array = np.ones((n, m))
border_array[1:-1, 1:-1] = 0
print("\n8. 2D array with 1 on border and 0 inside:\n", border_array)

# 9. Create an 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  # Fill odd rows, even columns
checkerboard[::2, 1::2] = 1  # Fill even rows, odd columns
print("\n9. 8x8 checkerboard pattern:\n", checkerboard)

1. Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix with values 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array of size 30:
 [0.73794806 0.25919963 0.98983525 0.43604803 0.89569261 0.32560402
 0.02339878 0.21587516 0.7088657  0.43838307 0.40633802 0.30051986
 0.07201901 0.21639378 0.66250161 0.75952832 0.5046043  0.08924145
 0.29326032 0.99911596 0.74086513 0.45657701 0.56331542 0.19447537
 0.14465841 0.1529689  0.96209392 0.7815585  0.98330034 0.7742441 ]
Mean of random array: 0.5029476677449339

5. 10x10 random array:
 [[0.9891775  0.0197313  0.70013616 0.48537812 0.99643957 0.4767939
  0.32211347 0.95961924 0.9490042  0.31647629]
 [0.01969755 0.71875905 0.38263193 0.14629648 0.90825485 0.12282373
  0.79072983 0.53129468 0.41903297 0.66216509]
 [0.79974836 0.81282362 0.10200747 0.76667645 0.5752

In [ ]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_xy = x + y
print("1. x + y =\n", add_xy)

# 2. Subtract the two arrays
sub_xy = x - y
print("\n2. x - y =\n", sub_xy)

# 3. Multiply the array with an integer (e.g., 3)
mult_x = x * 3
print("\n3. x * 3 =\n", mult_x)

# 4. Find the square of each element of the array
square_x = x ** 2
print("\n4. Square of x =\n", square_x)

# 5. Find the dot product
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)  # x is 2x2, v is 2-element vector
dot_xy = np.dot(x, y)
print("\n5. Dot products:")
print("v . w =", dot_vw)
print("x . v =", dot_xv)
print("x . y =\n", dot_xy)

# 6. Concatenate x and y along rows (axis=0) and v and w along columns
concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.column_stack((v, w))  # Alternative to concatenate along column
print("\n6. Concatenated x and y along rows:\n", concat_xy_row)
print("Concatenated v and w along columns:\n", concat_vw_col)

# 7. Concatenate x and v; will raise an error due to shape mismatch
try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    concat_xv_error = str(e)
    print("\n7. Attempt to concatenate x and v resulted in error:\n", concat_xv_error)
    print("Explanation: x has shape (2,2) while v has shape (2,). Cannot concatenate along axis=0 due to incompatible shapes.")

1. x + y =
 [[ 6  8]
 [10 13]]

2. x - y =
 [[-4 -4]
 [-4 -3]]

3. x * 3 =
 [[ 3  6]
 [ 9 15]]

4. Square of x =
 [[ 1  4]
 [ 9 25]]

5. Dot products:
v . w = 219
x . v = [29 77]
x . y =
 [[19 22]
 [50 58]]

6. Concatenated x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenated v and w along columns:
 [[ 9 11]
 [10 12]]

7. Attempt to concatenate x and v resulted in error:
 all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: x has shape (2,2) while v has shape (2,). Cannot concatenate along axis=0 due to incompatible shapes.


In [ ]:
import numpy as np

# Given matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
identity_check = np.dot(A, A_inv)
print("1. A * A^-1 =\n", identity_check)
print("Check if identity (approx):", np.allclose(identity_check, np.eye(2)))

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. AB =\n", AB)
print("BA =\n", BA)
print("Check AB != BA:", not np.allclose(AB, BA))

# 3. Prove (AB)^T = B^T * A^T
AB_T = (np.dot(A, B)).T
B_T_A_T = np.dot(B.T, A.T)
print("\n3. (AB)^T =\n", AB_T)
print("B^T * A^T =\n", B_T_A_T)
print("Check equality:", np.allclose(AB_T, B_T_A_T))

# ------------------------------------------------------------
# Solve the system of linear equations using inverse method
# Equations:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

# Represent in matrix form AX = B
A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

# Solve using inverse method
A_eq_inv = np.linalg.inv(A_eq)
X = np.dot(A_eq_inv, B_eq)
print("\nSolution of the system [x, y, z]:", X)

# Optional: Solve using np.linalg.solve (more stable)
X_solve = np.linalg.solve(A_eq, B_eq)
print("Solution using np.linalg.solve:", X_solve)

1. A * A^-1 =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Check if identity (approx): True

2. AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
Check AB != BA: True

3. (AB)^T =
 [[23 51]
 [13 29]]
B^T * A^T =
 [[23 51]
 [13 29]]
Check equality: True

Solution of the system [x, y, z]: [ 2.  1. -2.]
Solution using np.linalg.solve: [ 2.  1. -2.]


In [ ]:
import numpy as np
import time

# ----------------------------
# 1. Element-wise Addition
size = 1_000_000

# Python Lists
list1 = list(range(size))
list2 = list(range(size))
start = time.time()
list_add = [a + b for a, b in zip(list1, list2)]
end = time.time()
print(f"1. Python list element-wise addition took: {end - start:.5f} seconds")

# Numpy Arrays
arr1 = np.arange(size)
arr2 = np.arange(size)
start = time.time()
arr_add = arr1 + arr2
end = time.time()
print(f"   NumPy array element-wise addition took: {end - start:.5f} seconds\n")

# ----------------------------
# 2. Element-wise Multiplication

# Python Lists
start = time.time()
list_mult = [a * b for a, b in zip(list1, list2)]
end = time.time()
print(f"2. Python list element-wise multiplication took: {end - start:.5f} seconds")

# Numpy Arrays
start = time.time()
arr_mult = arr1 * arr2
end = time.time()
print(f"   NumPy array element-wise multiplication took: {end - start:.5f} seconds\n")

# ----------------------------
# 3. Dot Product

# Python Lists
start = time.time()
dot_list = sum(a * b for a, b in zip(list1, list2))
end = time.time()
print(f"3. Python list dot product took: {end - start:.5f} seconds")

# Numpy Arrays
start = time.time()
dot_array = np.dot(arr1, arr2)
end = time.time()
print(f"   NumPy array dot product took: {end - start:.5f} seconds\n")

# ----------------------------
# 4. Matrix Multiplication
matrix_size = 1000

# Python Lists (nested lists)
list_matrix1 = [[i + j for j in range(matrix_size)] for i in range(matrix_size)]
list_matrix2 = [[i - j for j in range(matrix_size)] for i in range(matrix_size)]

start = time.time()
# Naive matrix multiplication with Python lists
result_matrix = [[sum(a * b for a, b in zip(row, col)) for col in zip(*list_matrix2)] for row in list_matrix1]
end = time.time()
print(f"4. Python list 1000x1000 matrix multiplication took: {end - start:.5f} seconds")

# Numpy Arrays
np_matrix1 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)
np_matrix2 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)

start = time.time()
np_result = np.matmul(np_matrix1, np_matrix2)
end = time.time()
print(f"   NumPy 1000x1000 matrix multiplication took: {end - start:.5f} seconds")

1. Python list element-wise addition took: 0.18181 seconds
   NumPy array element-wise addition took: 0.00485 seconds

2. Python list element-wise multiplication took: 0.07568 seconds
   NumPy array element-wise multiplication took: 0.00541 seconds

3. Python list dot product took: 0.11182 seconds
   NumPy array dot product took: 0.00246 seconds

4. Python list 1000x1000 matrix multiplication took: 181.24493 seconds
   NumPy 1000x1000 matrix multiplication took: 2.42691 seconds
